const DICTIONARY = {
    en: {
        CURRENT_PLAYER: "Player",
        TURN_MSG: "it's your turn.",
        ENTER_MOVE: "Enter your move (row col): ",
        INVALID_MOVE: "Invalid move. Please try again.",
        DRAW_MSG: "It's a draw!",
        WIN_MSG: "Player",
        PLAY_AGAIN_QUESTION: "Do you want to play again? (yes/no): ",
        CONFIRM: "y",
        START_GAME: "Start Game",
        SETTINGS: "Settings",
        EXIT: "Exit",
        SELECT_OPTION: "Select an option: ",
        EXITING: "Exiting...",
        INVALID_CHOICE: "Invalid choice, please try again.",
        GAME_MODE: "Game Mode",
        PLAYER_X: "X",
        PLAYER_O: "O",
        GAME_TITLE: "Tic-Tac-Toe Game",
        GAME_DESCRIPTION: "The ultimate battle: Player vs. Player (CPU Mode)",
        LANGUAGE_MENU_TITLE: "===== Language Menu =====",
        LANGUAGE_CHANGED: "Language has been changed.",
        CHOOSE_LANGUAGE: "Choose a language: ",
        ENGLISH: "English",
        NORWEGIAN: "Norwegian",
        GAME_MODE_MENU_TITLE: "===== Game Mode Menu =====",
        GAME_MODE_PVP: "Player vs Player (PvP)",
        GAME_MODE_PVC: "Player vs Computer (PvC)",
        GAME_MODE_CHANGED: "Game mode changed to",
        INVALID_OPTION: "Invalid option. Please try again."
    },
    no: {
        CURRENT_PLAYER: "Spiller",
        TURN_MSG: "det er din tur.",
        ENTER_MOVE: "Skriv inn trekk (rad kolonne): ",
        INVALID_MOVE: "Ugyldig trekk. Prøv igjen.",
        DRAW_MSG: "Det er uavgjort!",
        WIN_MSG: "Spiller",
        PLAY_AGAIN_QUESTION: "Vil du spille igjen? (ja/nei): ",
        CONFIRM: "j",
        START_GAME: "Start Spillet",
        SETTINGS: "Innstillinger",
        EXIT: "Avslutt",
        SELECT_OPTION: "Velg et alternative: ",
        EXITING: "Avslutter...",
        INVALID_CHOICE: "Ugyldig valg, vennligst prøv igjen.",
        GAME_MODE: "Spillmodus",
        PLAYER_X: "X",
        PLAYER_O: "O",
        GAME_TITLE: "Tic-Tac-Toe Spill",
        GAME_DESCRIPTION: "Den ultimate kampen: Spiller mot Spiller (CPU Mode)",
        LANGUAGE_MENU_TITLE: "===== Språkmeny =====",
        LANGUAGE_CHANGED: "Språket er endret.",
        CHOOSE_LANGUAGE: "Velg et språk: ",
        ENGLISH: "Engelsk",
        NORWEGIAN: "Norsk",
        GAME_MODE_MENU_TITLE: "===== Spillmodusmeny =====",
        GAME_MODE_PVP: "Spiller mot spiller (PvP)",
        GAME_MODE_PVC: "Spiller mot datamaskin (PvC)",
        GAME_MODE_CHANGED: "Spillmodus endret til",
        INVALID_OPTION: "Ugyldig valg. Prøv igjen."
    }
};

export default DICTIONARY;
